### ISSUE TITLE
Unable to adjust camera settings from android

### ISSUE THREAD

**Issue by gabeduke** [timelapseplus/VIEW#2]
The web app does not register touch events for the Shutter/Aperture/ISO dropdowns on Android.

**Comment by elijahparker** [comment]
Is this with the chrome browser?  Chrome on iOS works for me -- I'll have to try an Android simulator

**Comment by gabeduke** [comment]
Correct, this is chrome browser. I've attempted to access the dropdown
menus on 2 different android devices.

**Comment by jimlob** [comment]
I have just tested this and found that Chrome won't work as you have mentioned, but the internet browser that came with pre-installed with my Samsung s5 works just fine. 

Samsung S5 Andriod version 6.0.1
View version 1.42
Samsung internet browser version 4.0.30-28

**Comment by gabeduke** [comment]
Tested in the beta builds and working as expected.
