### ISSUE TITLE
Context Button in Wifi Setting (1.4.0 and 1.4.1)

### ISSUE THREAD

**Issue by next4u** [timelapseplus/VIEW#3]
Not working in 1.4.0 and 1.4.1. Downgrade to 1.3.2 works.

**Comment by elijahparker** [comment]
Just restarting the VIEW or switching firmware versions will fix this (or, as you have experienced, occasionally cause it).  It's not actually tied to any specific firmware version, so I would recommend staying with v1.4.0 -- when you switch back it will likely work.

This is actually a low-level driver issue that's been there all along, it just rarely shows up.  I am going to replace the driver I'm using and go with a kernel module instead.  The new kernel provided in v1.4.0 has the necessary modules for this, and I hope to drop the old driver in the next release, fixing this issue.

**Comment by next4u** [comment]
above described works

**Comment by elijahparker** [comment]
This should now be fixed in v1.5.0 and newer
