### ISSUE TITLE
v1.8-beta85 - ISO control not working with Z6 

### ISSUE THREAD

**Issue by photonclock** [timelapseplus/VIEW#33]
Using the TLView+ app on iPhone
Connect to Nikon Z6 (firmware v2.0)
Z6 has auto-ISO disabled, ISO manually set to 100
In TLView app, go to Capture, enable Live View
Change aperture: works
Change shutter: works
Change ISO: no response
ISO also does not appear to be adjusting during a timelapse run (mode = Shutter + ISO), Aux2 input

If I change ISO on the camera via the "i" menu while the View app is in Capture mode with Live View on, the ISO updates in the View app immediately, so communication is definitely working from camera to View - but the View cannot seem to change/control the Z6 ISO.

**Comment by elijahparker** [comment]
Thanks for the report! Can you also send a log report from the VIEW after
attempting to change the ISO?

What was the current ISO? Does the app display the correct current ISO?

 If you change the ISO on the camera, does the app update?

Thanks!

Elijah

**Comment by photonclock** [comment]
Per numerous off-thread FB conversations, all resolved in v1.8beta88  Thank you Elijah!  Z6 is working quite nicely now.
