### ISSUE TITLE
Crash when connecting to TL+VIEW App during timelapse

### ISSUE THREAD

**Issue by gabeduke** [timelapseplus/VIEW#4]
I sent the log with 4 images from a Canon 6D
- Auto Ramping
- Fixed Interval

Connecting to the TL+VIEW App seems to reliably crash the module on v1.6.0 Beta12 Thanks!

**Comment by elijahparker** [comment]
Thanks for the report!  However the log file is only showing the current session, not the crash.  If you send the log again via Time-lapse Clips->(menu button)->Send log for review, I should get the relevant log.  Thanks!

**Comment by gabeduke** [comment]
Oops! I sent a couple logs from test clips earlier today. I think they had
around ~4 frames each. Let me know if there's any repro issues.

**Comment by elijahparker** [comment]
Thanks!  I'v got what I need now -- it's related to an empty keyframe set.  I put a fix in to avoid the crash (not committed yet), but I'll also dig a little deeper into the core issue yet.  I'll make sure it's fixed for the official 1.6.0 release.  Thanks for the help!
