### ISSUE TITLE
Issue wit updating firmware

### ISSUE THREAD

**Issue by EirikFisk** [timelapseplus/VIEW#8]
Hi,

Not sure if the server for firmwares is down? Have tried both through my phone and through my home wifi. 
It says downloading and sometimes extracting, but it never finishes...

@1.5.0 now

have tried several days now.
Have sent logs, hope it helps.

Eirik

**Comment by elijahparker** [comment]
Hi Eirik,

Now that v1.6.3 is out, it should be able to update to that.  Also, make sure bluetooth is disabled before updating as it may sometimes interfere.

Let me know if that works.

Thanks!

Elijah

**Comment by EirikFisk** [comment]
It worked! Thanks a bunch for your support, much appreciated!
